//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballTransfers.ADOApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootballTransfersEntities : DbContext
    {
        public FootballTransfersEntities()
            : base("name=FootballTransfersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Characterics> Characterics { get; set; }
        public virtual DbSet<FootballClubs> FootballClubs { get; set; }
        public virtual DbSet<Footballers> Footballers { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TransfersHistory> TransfersHistory { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
