//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballTransfers.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransfersHistory
    {
        public int Transfer_Id { get; set; }
        public int Footballer_Id { get; set; }
        public int Characteristic_Id { get; set; }
        public int ClubOfSale { get; set; }
        public int ClubOfPurchase { get; set; }
        public int TransferCost { get; set; }
        public System.DateTime DateAndTime { get; set; }
    
        public virtual FootballClubs FootballClubs { get; set; }
        public virtual FootballClubs FootballClubs1 { get; set; }
        public virtual Footballers Footballers { get; set; }
    }
}
